export type WineTourRegion = 'krasnodar' | 'crimea'
export type WineTourFormat = 'tasting' | 'excursion' | 'sunset'
export type WineTourTone = 'plum' | 'sage' | 'amber'

export interface WineTourProgramItem {
  time: string
  title: string
  description: string
}

export interface WineTour {
  id: string
  title: string
  winery: string
  region: WineTourRegion
  regionLabel: string
  location: string
  format: WineTourFormat
  formatLabel: string
  duration: string
  price: number
  groupLabel: string
  coordinates: { lat: number, lng: number }
  image: string
  imageAlt: string
  tone: WineTourTone
  summary: string
  includes: string[]
  program: WineTourProgramItem[]
  sourceUrl?: string
  sourceCheckedAt?: string
  bookingNote?: string
  ageRestriction?: '0+' | '18+'
}

const crimeaSourceCheckedAt = '27.09.2026'
const vineyardImage = '/images/tours/vineyard-route.webp'
const cellarImage = '/images/tours/balaklava-cellar.webp'

export const wineTours: WineTour[] = [
  {
    id: 'golden-balka-intro',
    title: 'Знакомство с «Золотой Балкой»',
    winery: 'Золотая Балка',
    region: 'crimea',
    regionLabel: 'Крым',
    location: 'Балаклава',
    format: 'excursion',
    formatLabel: 'Экскурсия + дегустация',
    duration: '1 час',
    price: 1300,
    groupLabel: 'от 2 гостей',
    coordinates: { lat: 44.50, lng: 33.60 },
    image: cellarImage,
    imageAlt: 'Иллюстрация винного погреба и дегустационного пространства',
    tone: 'plum',
    summary: 'Базовый маршрут по винодельне с историей Балаклавского терруара, производством и дегустацией.',
    includes: ['Винный подвал', 'Цех розлива', 'Дегустация'],
    program: [
      { time: '00:00', title: 'Балаклавский терруар', description: 'Знакомство с историей хозяйства и виноделия долины.' },
      { time: '00:20', title: 'Винный подвал', description: 'Маршрут по производству и демонстрационной площадке цеха розлива.' },
      { time: '00:45', title: 'Дегустация', description: 'Завершение программы знакомством с винами хозяйства.' },
    ],
    sourceUrl: 'https://zbtour.ru/catalog/ekskursii/',
    sourceCheckedAt: crimeaSourceCheckedAt,
    bookingNote: 'На официальном сайте доступны даты и время; в высокий сезон лучше бронировать заранее.',
    ageRestriction: '18+',
  },
  {
    id: 'golden-balka-sparkling',
    title: 'Дегустация игристых вин',
    winery: 'Золотая Балка',
    region: 'crimea',
    regionLabel: 'Крым',
    location: 'Балаклава',
    format: 'tasting',
    formatLabel: 'Дегустация',
    duration: '30–35 минут',
    price: 900,
    groupLabel: 'от 2 гостей',
    coordinates: { lat: 44.50, lng: 33.60 },
    image: cellarImage,
    imageAlt: 'Иллюстрация дегустационного пространства винодельни',
    tone: 'plum',
    summary: 'Короткая дегустация шести образцов игристых вин — от брюта до полусладкого.',
    includes: ['6 образцов', 'Игристые вина', 'Сопровождение'],
    program: [
      { time: '00:00', title: 'Введение', description: 'Гид объясняет стили и технологию игристых вин.' },
      { time: '00:10', title: 'Шесть образцов', description: 'Последовательная дегустация от брюта до полусладкого.' },
      { time: '00:30', title: 'Вопросы', description: 'Короткое завершение и рекомендации по выбору.' },
    ],
    sourceUrl: 'https://zbtour.ru/catalog/ekskursii/',
    sourceCheckedAt: crimeaSourceCheckedAt,
    bookingNote: 'Дегустационные программы доступны только совершеннолетним гостям.',
    ageRestriction: '18+',
  },
  {
    id: 'winepark-intro',
    title: 'Знакомство с Винным парком',
    winery: 'WINEPARK',
    region: 'crimea',
    regionLabel: 'Крым',
    location: 'Понизовка',
    format: 'excursion',
    formatLabel: 'Архитектура + парк',
    duration: '1 час',
    price: 3000,
    groupLabel: 'по билету',
    coordinates: { lat: 44.40, lng: 33.96 },
    image: vineyardImage,
    imageAlt: 'Иллюстрация современного винного комплекса среди виноградников',
    tone: 'sage',
    summary: 'Обзорный маршрут по пространству WINEPARK для знакомства с архитектурой, ландшафтом и идеей проекта.',
    includes: ['Архитектура', 'Ландшафт', 'Винный парк'],
    program: [
      { time: '00:00', title: 'Встреча в парке', description: 'Знакомство с устройством пространства и маршрутом.' },
      { time: '00:20', title: 'Архитектура и ландшафт', description: 'Прогулка по главным объектам винного комплекса.' },
      { time: '00:50', title: 'Панорама', description: 'Финальная точка маршрута с видами Южного берега.' },
    ],
    sourceUrl: 'https://winepark.ru/afisha/',
    sourceCheckedAt: crimeaSourceCheckedAt,
    bookingNote: 'Формат 0+; доступность конкретного времени проверяется в афише WINEPARK.',
    ageRestriction: '0+',
  },
  {
    id: 'winepark-winery',
    title: 'Экскурсия по винодельне WINEPARK',
    winery: 'WINEPARK',
    region: 'crimea',
    regionLabel: 'Крым',
    location: 'Понизовка',
    format: 'excursion',
    formatLabel: 'Производство',
    duration: '1,5 часа',
    price: 1700,
    groupLabel: 'по билету',
    coordinates: { lat: 44.40, lng: 33.96 },
    image: cellarImage,
    imageAlt: 'Иллюстрация пространства современной винодельни',
    tone: 'sage',
    summary: 'Экскурсионный маршрут по современной гравитационной винодельне без дегустационной части.',
    includes: ['Винодельня', 'Производственные уровни', 'Технологии'],
    program: [
      { time: '00:00', title: 'Вводная часть', description: 'Как устроена гравитационная винодельня.' },
      { time: '00:30', title: 'Производственный маршрут', description: 'Путь винограда через основные уровни комплекса.' },
      { time: '01:15', title: 'Вопросы гиду', description: 'Финальное обсуждение технологий и терруара.' },
    ],
    sourceUrl: 'https://winepark.ru/afisha/',
    sourceCheckedAt: crimeaSourceCheckedAt,
    bookingNote: 'Формат 0+ и подходит тем, кто хочет посетить производство без дегустации.',
    ageRestriction: '0+',
  },
  {
    id: 'winepark-winery-tasting',
    title: 'Винодельня с дегустацией WINEPARK',
    winery: 'WINEPARK',
    region: 'crimea',
    regionLabel: 'Крым',
    location: 'Понизовка',
    format: 'tasting',
    formatLabel: 'Экскурсия + дегустация',
    duration: '1 час',
    price: 3000,
    groupLabel: 'по билету',
    coordinates: { lat: 44.40, lng: 33.96 },
    image: cellarImage,
    imageAlt: 'Иллюстрация дегустации в современной винодельне',
    tone: 'amber',
    summary: 'Компактная экскурсия по винодельне с финальной дегустацией вин WINEPARK.',
    includes: ['Винодельня', 'Дегустация', 'Сомелье'],
    program: [
      { time: '00:00', title: 'Как устроена винодельня', description: 'Короткий маршрут по ключевым производственным зонам.' },
      { time: '00:30', title: 'От технологии к вкусу', description: 'Связываем этапы производства со стилем вина.' },
      { time: '00:40', title: 'Дегустация', description: 'Знакомство с винами проекта под сопровождением специалиста.' },
    ],
    sourceUrl: 'https://winepark.ru/afisha/',
    sourceCheckedAt: crimeaSourceCheckedAt,
    bookingNote: 'Программа 18+; актуальные сеансы и состав дегустации указаны в афише.',
    ageRestriction: '18+',
  },
  {
    id: 'winepark-autochthons',
    title: 'Дегустация «Автохтоны»',
    winery: 'WINEPARK',
    region: 'crimea',
    regionLabel: 'Крым',
    location: 'Понизовка',
    format: 'tasting',
    formatLabel: 'Тематическая дегустация',
    duration: '1 час',
    price: 1900,
    groupLabel: 'по билету',
    coordinates: { lat: 44.40, lng: 33.96 },
    image: vineyardImage,
    imageAlt: 'Иллюстрация крымского виноградника',
    tone: 'amber',
    summary: 'Тематическая дегустация для знакомства с локальными сортами и характером крымского терруара.',
    includes: ['Автохтонные сорта', 'Дегустационный сет', 'Рассказ сомелье'],
    program: [
      { time: '00:00', title: 'Что такое автохтон', description: 'Короткое введение в локальные сорта и географию.' },
      { time: '00:15', title: 'Дегустационный сет', description: 'Сравнение вин и характерных ароматических профилей.' },
      { time: '00:50', title: 'Карта вкуса', description: 'Итоги и персональные ориентиры для дальнейшего выбора.' },
    ],
    sourceUrl: 'https://winepark.ru/afisha/',
    sourceCheckedAt: crimeaSourceCheckedAt,
    bookingNote: 'Программа 18+; состав сета может меняться.',
    ageRestriction: '18+',
  },
  {
    id: 'inkerman-underground',
    title: 'Экскурсия INKERMAN с дегустацией',
    winery: 'INKERMAN',
    region: 'crimea',
    regionLabel: 'Крым',
    location: 'Инкерман',
    format: 'tasting',
    formatLabel: 'Подвалы + дегустация',
    duration: '1,5 часа',
    price: 1200,
    groupLabel: 'по записи',
    coordinates: { lat: 44.61, lng: 33.61 },
    image: cellarImage,
    imageAlt: 'Иллюстрация подземных винных галерей',
    tone: 'plum',
    summary: 'Маршрут по подземным галереям глубиной до 30 метров и дегустация восьми тихих вин INKERMAN.',
    includes: ['Подземные галереи', 'История завода', '8 образцов'],
    program: [
      { time: '00:00', title: 'Подземный город', description: 'История известняковых выработок и создания завода.' },
      { time: '00:35', title: 'Галереи выдержки', description: 'Знакомство с бочками, бутами и условиями хранения вина.' },
      { time: '01:00', title: 'Восемь тихих вин', description: 'Дегустационный сет с объяснением стилей хозяйства.' },
    ],
    sourceUrl: 'https://inkerman.ru/catalog/ekskursii/ekskursiya-v-inkerman-s-degustatsiey/',
    sourceCheckedAt: crimeaSourceCheckedAt,
    bookingNote: 'Только по предварительной записи; программа предназначена для гостей 18+.',
    ageRestriction: '18+',
  },
  {
    id: 'alma-valley-standard',
    title: 'Alma Taste «Стандарт»',
    winery: 'Alma Valley',
    region: 'crimea',
    regionLabel: 'Крым',
    location: 'Вилино',
    format: 'tasting',
    formatLabel: 'Экскурсия + дегустация',
    duration: '1,5–2 часа',
    price: 2500,
    groupLabel: 'сборная группа',
    coordinates: { lat: 44.84, lng: 33.68 },
    image: vineyardImage,
    imageAlt: 'Иллюстрация современной винодельни в долине',
    tone: 'sage',
    summary: 'Гравитационная винодельня от верхней смотровой площадки до цеха выдержки и дегустация семи вин.',
    includes: ['Гравитационная винодельня', 'Производство', '7 вин'],
    program: [
      { time: '00:00', title: 'Смотровая площадка', description: 'Начало маршрута на высоте над производственными цехами.' },
      { time: '00:30', title: 'От переработки до выдержки', description: 'Последовательный проход по уровням винодельни.' },
      { time: '01:05', title: 'Alma Taste', description: 'Дегустация семи вин из четырёх линеек.' },
    ],
    sourceUrl: 'https://www.alma-valley.ru/wine-tourism.html',
    sourceCheckedAt: crimeaSourceCheckedAt,
    bookingNote: 'Предварительная запись обязательна; программы проходят со вторника по субботу.',
    ageRestriction: '18+',
  },
  {
    id: 'alma-valley-vip',
    title: 'Alma Taste «ВИП»',
    winery: 'Alma Valley',
    region: 'crimea',
    regionLabel: 'Крым',
    location: 'Вилино',
    format: 'tasting',
    formatLabel: 'Премиальная дегустация',
    duration: '1,5–2 часа',
    price: 4000,
    groupLabel: 'сборная группа',
    coordinates: { lat: 44.84, lng: 33.68 },
    image: cellarImage,
    imageAlt: 'Иллюстрация премиального дегустационного зала',
    tone: 'amber',
    summary: 'Экскурсия по винодельне и семь вин сортовой и премиальной линеек с лёгкими закусками.',
    includes: ['Экскурсия', '7 премиальных вин', 'Лёгкие закуски'],
    program: [
      { time: '00:00', title: 'Архитектура винодельни', description: 'Знакомство с гравитационным принципом производства.' },
      { time: '00:40', title: 'Погреб и выдержка', description: 'Современное оборудование и парк дубовых бочек.' },
      { time: '01:10', title: 'Премиальный сет', description: 'Семь вин, закуски и приветственный бокал игристого.' },
    ],
    sourceUrl: 'https://www.alma-valley.ru/wine-tourism.html',
    sourceCheckedAt: crimeaSourceCheckedAt,
    bookingNote: 'Предварительная запись обязательна; позиции в дегустационном сете могут заменяться.',
    ageRestriction: '18+',
  },
  {
    id: 'new-world-historical',
    title: 'Экскурсионный тур «Исторический»',
    winery: 'Новый Свет',
    region: 'crimea',
    regionLabel: 'Крым',
    location: 'Новый Свет',
    format: 'excursion',
    formatLabel: 'История без дегустации',
    duration: '40 минут',
    price: 600,
    groupLabel: 'от 4 гостей',
    coordinates: { lat: 44.83, lng: 34.91 },
    image: cellarImage,
    imageAlt: 'Иллюстрация исторических винных тоннелей',
    tone: 'plum',
    summary: 'Прогулка по тоннелям XIX века с историей Дома шампанских вин и князя Льва Голицына.',
    includes: ['Тоннели XIX века', 'История хозяйства', 'Без дегустации'],
    program: [
      { time: '00:00', title: 'Дом шампанских вин', description: 'Начало истории хозяйства и классического метода.' },
      { time: '00:10', title: 'Тоннели Коба-Кая', description: 'Маршрут по историческому тоннельному хозяйству.' },
      { time: '00:35', title: 'Наследие Голицына', description: 'Завершение рассказом об основоположнике российского виноделия.' },
    ],
    sourceUrl: 'https://nsvet-crimea.ru/tours/ekskursionnyy-tur-istoricheskiy/',
    sourceCheckedAt: crimeaSourceCheckedAt,
    bookingNote: 'Дегустация не предусмотрена; билеты продаются в кассе перед входом.',
    ageRestriction: '18+',
  },
  {
    id: 'new-world-wine-historical',
    title: 'Винный тур «Исторический»',
    winery: 'Новый Свет',
    region: 'crimea',
    regionLabel: 'Крым',
    location: 'Новый Свет',
    format: 'tasting',
    formatLabel: 'Тоннели + дегустация',
    duration: '1 час 20 минут',
    price: 1400,
    groupLabel: '15–40 гостей',
    coordinates: { lat: 44.83, lng: 34.91 },
    image: cellarImage,
    imageAlt: 'Иллюстрация старинных тоннелей для выдержки игристых вин',
    tone: 'plum',
    summary: 'Исторические тоннели и дегустация пяти популярных шампанских и игристых вин «Нового Света».',
    includes: ['Тоннели', '5 игристых вин', 'История Голицына'],
    program: [
      { time: '00:00', title: 'История «Нового Света»', description: 'Имение, князь Голицын и появление российского шампанского.' },
      { time: '00:25', title: 'Подземные тоннели', description: 'Как выдерживаются бутылки и работает классический метод.' },
      { time: '00:50', title: 'Пять игристых вин', description: 'Дегустация популярных марок Дома шампанских вин.' },
    ],
    sourceUrl: 'https://nsvet-crimea.ru/tours/',
    sourceCheckedAt: crimeaSourceCheckedAt,
    bookingNote: 'Программа 18+; билеты приобретаются в кассе, расписание лучше уточнить заранее.',
    ageRestriction: '18+',
  },
  {
    id: 'new-world-premium',
    title: 'Винный тур «Премиум»',
    winery: 'Новый Свет',
    region: 'crimea',
    regionLabel: 'Крым',
    location: 'Новый Свет',
    format: 'tasting',
    formatLabel: 'Премиальный тур',
    duration: '1,5 часа',
    price: 2100,
    groupLabel: 'от 10 гостей',
    coordinates: { lat: 44.83, lng: 34.91 },
    image: cellarImage,
    imageAlt: 'Иллюстрация исторического дегустационного погреба',
    tone: 'amber',
    summary: 'Расширенный маршрут по голицынским подвалам с дегустацией шести марок шампанского и игристого вина.',
    includes: ['Голицынские подвалы', '6 образцов', 'Премиальный формат'],
    program: [
      { time: '00:00', title: 'Путешествие в XIX век', description: 'История имения и Академии виноделия князя Голицына.' },
      { time: '00:35', title: 'Лабиринты подвалов', description: 'Тоннели, которые посещал Николай II со свитой.' },
      { time: '01:00', title: 'Шесть марок', description: 'Дегустация шампанского и игристых вин.' },
    ],
    sourceUrl: 'https://nsvet-crimea.ru/tours/vinnyy-tur-paradiz/',
    sourceCheckedAt: crimeaSourceCheckedAt,
    bookingNote: 'Программа 18+ проводится для групп; актуальное время нужно подтвердить у винодельни.',
    ageRestriction: '18+',
  },
  {
    id: 'uppa-biodynamic',
    title: 'Биодинамическая винодельня в горах',
    winery: 'Uppa Winery',
    region: 'crimea',
    regionLabel: 'Крым',
    location: 'Родное',
    format: 'tasting',
    formatLabel: 'Винодел + дегустация',
    duration: '1,5–2 часа',
    price: 6000,
    groupLabel: 'до 14 гостей',
    coordinates: { lat: 44.5610515, lng: 33.7506151 },
    image: vineyardImage,
    imageAlt: 'Иллюстрация горного виноградника',
    tone: 'sage',
    summary: 'Высокогорный виноградник, гравитационное производство и погреб с гидом-виноделом или сомелье хозяйства.',
    includes: ['Виноградники', 'Гравитационная винодельня', 'Панорамный зал'],
    program: [
      { time: '00:00', title: 'Виноградники на высоте', description: 'Биодинамика, ручной труд и крымский Кокур.' },
      { time: '00:35', title: 'Гравитационное производство', description: 'Танки, прессы, ферментация и линия розлива.' },
      { time: '01:15', title: 'Бочковая выдержка', description: 'Французский дуб и завершение в панорамном дегустационном зале.' },
    ],
    sourceUrl: 'https://uppawinery.ru/visit/winery',
    sourceCheckedAt: crimeaSourceCheckedAt,
    bookingNote: 'Посещение только по предварительной записи с подтверждением винодельни.',
    ageRestriction: '18+',
  },
  {
    id: 'sikory-sunset',
    title: 'Закат на винограднике',
    winery: 'Усадьба Сикоры',
    region: 'krasnodar',
    regionLabel: 'Краснодарский край',
    location: 'Новороссийск',
    format: 'sunset',
    formatLabel: 'Закат',
    duration: '2,5 часа',
    price: 6000,
    groupLabel: 'до 8 гостей',
    coordinates: { lat: 44.72, lng: 37.77 },
    image: '/images/tours/novorossiysk-sunset.webp',
    imageAlt: 'Виноградники на склонах у Новороссийска в вечернем свете',
    tone: 'amber',
    summary: 'Неспешный маршрут по виноградникам, вид на вечернее побережье и дегустация в камерной группе.',
    includes: ['Прогулка с гидом', 'Дегустационный сет', 'Закатная площадка'],
    program: [
      { time: '00:00', title: 'Встреча у винодельни', description: 'Знакомимся с маршрутом и терруаром Семигорья.' },
      { time: '00:35', title: 'Дорога среди лоз', description: 'Поднимаемся к панорамной точке и разбираемся в сортах винограда.' },
      { time: '01:20', title: 'Дегустация на закате', description: 'Пробуем локальные вина и сохраняем понравившиеся в приложении.' },
    ],
  },
  {
    id: 'sikory-bestseller',
    title: 'Экскурсионно-дегустационный тур «Бестселлер»',
    winery: 'Усадьба Сикоры',
    region: 'krasnodar',
    regionLabel: 'Краснодарский край',
    location: 'Новороссийск',
    format: 'tasting',
    formatLabel: 'Экскурсия + дегустация',
    duration: '2 часа',
    price: 5000,
    groupLabel: 'до 10 гостей',
    coordinates: { lat: 44.72, lng: 37.77 },
    image: vineyardImage,
    imageAlt: 'Дорога, проходящая через виноградники к современной винодельне',
    tone: 'sage',
    summary: 'Путь от лозы до погреба с понятным разбором технологии и финальным сетом знаковых вин.',
    includes: ['Виноградники', 'Производство', 'Дегустационный сет'],
    program: [
      { time: '00:00', title: 'Терруар', description: 'Начинаем с климата, почвы и устройства виноградника.' },
      { time: '00:45', title: 'Винодельня', description: 'Проходим производственные зоны и заглядываем в погреб.' },
      { time: '01:20', title: 'Бестселлеры хозяйства', description: 'Сравниваем стили и отмечаем личных фаворитов.' },
    ],
  },
  {
    id: 'taman-masterclass',
    title: 'Мастер-класс в центре классического виноделия',
    winery: 'Кубань-Вино',
    region: 'krasnodar',
    regionLabel: 'Краснодарский край',
    location: 'Тамань',
    format: 'tasting',
    formatLabel: 'Мастер-класс',
    duration: '2 часа',
    price: 2500,
    groupLabel: 'до 10 гостей',
    coordinates: { lat: 45.21, lng: 36.72 },
    image: '/images/tours/novorossiysk-sunset.webp',
    imageAlt: 'Южный виноградник в мягком золотом свете',
    tone: 'amber',
    summary: 'Практическая встреча о классических стилях вина: от ароматики и температуры до уверенной дегустации.',
    includes: ['Экскурсия', 'Практика с сомелье', 'Дегустационный сет'],
    program: [
      { time: '00:00', title: 'Классическое виноделие', description: 'Знакомимся с центром и базовыми этапами производства.' },
      { time: '00:40', title: 'Практика дегустации', description: 'Учимся оценивать аромат, баланс и послевкусие без сложных терминов.' },
      { time: '01:30', title: 'Собственный профиль', description: 'Отмечаем любимые стили и получаем ориентиры для выбора вина.' },
    ],
  },
]
